services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    #    volumes:
    #      - .:/app:delegated
    #      - /app/node_modules
    command: npm run preview